# Generated by Django 5.1.15 on 2026-06-12 15:16

import accounts.models
import django.utils.timezone
from django.db import migrations, models


def copy_users(apps, schema_editor):
    """Recopie la/les ligne(s) de l'ancien auth_user (auth.User standard) dans
    la nouvelle table accounts_user, en conservant id + hash de mot de passe.

    DÉFENSIF : sur une base neuve / CI / SQLite, la table auth_user n'existe PAS
    (avec un AUTH_USER_MODEL custom, le CreateModel "swappable" de auth.0001 est
    un no-op → rien à copier). On ne fait donc rien dans ce cas. La copie doit
    vivre dans 0001 (et non plus tard) car la migration auto-générée qui re-pointe
    les FK de l'admin dépend de accounts '__first__' : la copie doit tourner AVANT
    que la FK django_admin_log.user ne soit re-pointée vers accounts_user.
    """
    conn = schema_editor.connection
    with conn.cursor() as c:
        if "auth_user" not in conn.introspection.table_names(c):
            return  # base neuve — rien à migrer
        c.execute(
            """INSERT INTO accounts_user
                (id, password, last_login, is_superuser, email, first_name,
                 last_name, is_staff, is_active, date_joined)
            SELECT id, password, last_login, is_superuser, email, first_name,
                 last_name, is_staff, is_active, date_joined
            FROM auth_user"""
        )
        # Garde la séquence d'id synchronisée pour que les nouveaux utilisateurs
        # n'entrent pas en collision avec les id copiés (PostgreSQL uniquement).
        if conn.vendor == "postgresql":
            c.execute(
                "SELECT setval(pg_get_serial_sequence('accounts_user','id'), "
                "COALESCE((SELECT MAX(id) FROM accounts_user), 1))"
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.RunPython(copy_users, noop),
    ]
