# Generated by Django 5.1.15 on 2026-05-31 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifiant URL')),
                ('category', models.CharField(blank=True, help_text='ex : Article, Événement, Atelier', max_length=60, verbose_name='Catégorie')),
                ('excerpt', models.TextField(blank=True, verbose_name='Résumé')),
                ('body', models.TextField(blank=True, verbose_name='Contenu')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('read_time', models.CharField(blank=True, max_length=30, verbose_name='Temps de lecture')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publiée')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['order', '-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='ex : accueil, qui-suis-je, agilite', unique=True, verbose_name='Identifiant URL')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('nav_label', models.CharField(blank=True, max_length=60, verbose_name='Libellé menu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('show_in_nav', models.BooleanField(default=True, verbose_name='Afficher dans le menu')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publiée')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='Titre SEO')),
                ('seo_description', models.CharField(blank=True, max_length=300, verbose_name='Description SEO')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('kind', models.CharField(choices=[('client', 'Client'), ('association', 'Association')], default='client', max_length=20, verbose_name='Type')),
                ('sector_or_cause', models.CharField(blank=True, max_length=120, verbose_name='Secteur / cause')),
                ('description', models.TextField(blank=True, verbose_name='Description / type de soutien')),
                ('support_type', models.CharField(blank=True, help_text='Associations : Sponsoring, Mécénat de compétences, Don…', max_length=80, verbose_name='Forme de soutien')),
                ('link', models.URLField(blank=True, verbose_name='Lien')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Logo')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Client / Association',
                'verbose_name_plural': 'Clients & Associations',
                'ordering': ['kind', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('sector', models.CharField(blank=True, help_text='ex : Banque, Retail, Santé, Public, Tech / SaaS', max_length=80, verbose_name='Secteur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('result', models.CharField(blank=True, help_text='ex : Lead-time −60 %', max_length=160, verbose_name='Résultat clé')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='foxugly', max_length=80, verbose_name='Nom de marque')),
                ('tagline', models.CharField(blank=True, default='Coaching agile indépendant', max_length=200, verbose_name='Accroche')),
                ('contact_email', models.EmailField(default='contact@foxugly.com', max_length=254, verbose_name='Email de contact')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('footer_text', models.TextField(blank=True, default="Coaching agile indépendant. J'aide vos équipes à livrer de la valeur, plus vite et plus sereinement.", verbose_name='Texte du pied de page')),
            ],
            options={
                'verbose_name': 'Réglages du site',
                'verbose_name_plural': 'Réglages du site',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='Citation')),
                ('author', models.CharField(max_length=120, verbose_name='Auteur')),
                ('role', models.CharField(blank=True, max_length=160, verbose_name='Rôle / société')),
                ('initials', models.CharField(blank=True, max_length=4, verbose_name='Initiales')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('hero', 'Hero (accueil)'), ('page_hero', 'En-tête de page'), ('richtext', 'Texte enrichi'), ('stats', 'Chiffres clés'), ('cards', 'Cartes (services / valeurs)'), ('timeline', 'Frise chronologique'), ('accordion', 'Accordéon'), ('testimonials', 'Témoignages'), ('logo_wall', 'Mur de logos'), ('news_list', "Liste d'actualités"), ('project_list', 'Liste de projets'), ('partner_list', 'Liste clients / associations'), ('cta', "Appel à l'action")], max_length=30, verbose_name='Type de bloc')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('anchor', models.SlugField(blank=True, help_text='Optionnel, pour les liens internes (ex : contact)', verbose_name='Ancre (#)')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Contenu')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='content.page')),
            ],
            options={
                'verbose_name': 'Bloc',
                'verbose_name_plural': 'Blocs',
                'ordering': ['page', 'order', 'id'],
            },
        ),
    ]
