# Generated by Django 5.1.15 on 2026-05-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('sent', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('error', models.TextField(blank=True, verbose_name="Erreur d'envoi")),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero (accueil)'), ('page_hero', 'En-tête de page'), ('richtext', 'Texte enrichi'), ('stats', 'Chiffres clés'), ('cards', 'Cartes (services / valeurs)'), ('timeline', 'Frise chronologique'), ('accordion', 'Accordéon'), ('testimonials', 'Témoignages'), ('logo_wall', 'Mur de logos'), ('news_list', "Liste d'actualités"), ('project_list', 'Liste de projets'), ('partner_list', 'Liste clients / associations'), ('cta', "Appel à l'action"), ('contact_form', 'Formulaire de contact')], max_length=30, verbose_name='Type de bloc'),
        ),
    ]
