# Generated by Django 5.1.15 on 2026-05-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contactmessage_alter_block_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_account',
            field=models.CharField(blank=True, max_length=60, verbose_name='Numéro de compte (IBAN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vat_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Numéro de TVA'),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero (accueil)'), ('page_hero', 'En-tête de page'), ('richtext', 'Texte enrichi'), ('stats', 'Chiffres clés'), ('cards', 'Cartes (services / valeurs)'), ('timeline', 'Frise chronologique'), ('accordion', 'Accordéon'), ('testimonials', 'Témoignages'), ('logo_wall', 'Mur de logos'), ('news_list', "Liste d'actualités"), ('project_list', 'Liste de projets'), ('partner_list', 'Liste clients / associations'), ('cta', "Appel à l'action"), ('contact_form', 'Formulaire de contact'), ('contact_info', 'Coordonnées (adresse, TVA, compte…)')], max_length=30, verbose_name='Type de bloc'),
        ),
    ]
