# Generated by Django 5.1.15 on 2026-06-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_clean_accueil_blocks'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['page', 'order'], name='content_blo_page_id_ba7d50_idx'),
        ),
    ]
